BRSK/Models/Brand.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace BRSK.Models
{
    public class Brand
    {
        public int BrandId { get; set; }
        public string Name { get; set; }
        public bool Activity { get; set; } = false;
        public ICollection<Model> BrandModels { get; set; }
        public Brand()
        {
            BrandModels = new Collection<Model>();
        }
    }
}

BRSK/Models/ErrorViewModel.cs
using System;

namespace BRSK.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BRSK/Models/Model.cs
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace BRSK.Models
{
    public class Model
    {
        public int ModelId { get; set; }
        public int BrandId { get; set; } = 1;
        public string Name { get; set; }
        public bool Activity { get; set; } = false;

        public Brand Brand { get; set; }
    }
}

BRSK/Models/PageModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections;

namespace BRSK.Models
{
    public class PageModel
    {
      public int PageModelId { get; set; }
      public  SelectList BrandList { get; set; }

      public string ModelName { get; set; }
      public int SelectedBrand { get; set; }
      public bool Activity { get; set; }
    }
}

BRSK/Controllers/BrandController.cs
using BRSK.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using BRSK.Models;

namespace BRSK.Controllers
{
    public class BrandController:Controller
    {

        private BRSKApplicationContext _context;
        public BrandController(BRSKApplicationContext context)
        {
            _context = context;

        }


        public async Task<IActionResult> Index()
        {
            return View(await _context.Brands.AsQueryable().ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Brand newbrand)
        {
           
            _context.Brands.Add(newbrand);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
       
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Brand brand = await _context.Brands.FirstOrDefaultAsync(brandItem => brandItem.BrandId == id);
                if (brand != null)
                    return View(brand);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Brand Brand)
        {
            _context.Brands.Update(Brand);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Brand brand = await _context.Brands.FirstOrDefaultAsync(brandItem => brandItem.BrandId == id);
                if (brand != null)
                    return View(brand);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Brand brand = await _context.Brands.FirstOrDefaultAsync(brandItem => brandItem.BrandId == id);
                if (brand != null)
                {
                    _context.Brands.Remove(brand);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
    }
}

BRSK/Controllers/HomeController.cs
using BRSK.Data;
using BRSK.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace BRSK.Controllers
{
    public class HomeController : Controller
    {

        private BRSKApplicationContext _context;
        public HomeController(BRSKApplicationContext context)
        {
            _context = context;

        }



        public async Task<IActionResult> Index()
        {
            var ModelList = await _context.Models.AsQueryable().Include(modelItem => modelItem.Brand).ToListAsync();
            return View(ModelList.OrderBy(item => item.Brand.Name).ToList());
        }
        
    }
}

BRSK/Controllers/ModelController.cs
using BRSK.Data;
using BRSK.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace BRSK.Controllers
{
    public class ModelController:Controller
    {


        private BRSKApplicationContext _context;
        public ModelController(BRSKApplicationContext context)
        {
            _context = context;

        }


        public async Task<IActionResult> Index()
        {
            return View(await _context.Models.AsQueryable().Include(modelItem => modelItem.Brand).ToListAsync());
        }
        public async Task<IActionResult> Create()
        {
            return View(new PageModel { BrandList = new SelectList(await _context.Brands.ToListAsync(), "BrandId", "Name") });
        }
        [HttpPost]
        public async Task<IActionResult> Create(PageModel pagemodel)
        {
            var model = new Model()
            {
                BrandId = pagemodel.SelectedBrand + 1,
                Name = pagemodel.ModelName,
                Activity = pagemodel.Activity
            };
            _context.Models.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
      
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Model model = await _context.Models.Include(modelItem => modelItem.Brand).FirstOrDefaultAsync(modelItem => modelItem.ModelId == id);
                if (model != null)
                    return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Model model)
        {
            _context.Models.Update(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Model model = await _context.Models.FirstOrDefaultAsync(modelItem => modelItem.ModelId == id);
                if (model != null)
                    return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Model model = await _context.Models.FirstOrDefaultAsync(modelItem => modelItem.ModelId == id);
                if (model != null)
                {
                    _context.Models.Remove(model);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

    }
}

BRSK/Views/Brand/Create.cshtml
@model BRSK.Models.Brand
@{
    ViewBag.Title = "Добавление нового бренда";
}
<form asp-action="create" asp-controller="Brand">

    <div class="form-group">
        <label asp-for="Name" class="control-label">Название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Activity" class="control-label">Наличие</label>
        <input type="checkbox" asp-for="Activity" value="true"/>
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

BRSK/Views/Brand/Delete.cshtml
@model BRSK.Models.Brand
@{
    ViewBag.Title = "Удаление модели машины";
}

<div>
    <dl class="dl-horizontal">
        <dt>Имя</dt>
        <dd>
            @Html.DisplayFor(brand => brand.Name)
        </dd>

        <dt>Brand Id</dt>
        <dd>
        @Html.DisplayFor(brand => brand.BrandId)
        </dd>
    </dl>

    <div>
        <form asp-controller="Brand" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

BRSK/Views/Brand/Edit.cshtml
@model BRSK.Models.Brand
@{
    ViewBag.Title = "Редактирование марки автомобилей";
}
<form asp-action="edit" asp-controller="Brand" asp-route-id="@Model.BrandId">
    <div class="form-group">
        <input asp-for="BrandId" type="hidden" />
        <label asp-for="Name" class="control-label">Наименование</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Activity" class="control-label">Наличие</label>
        <input type="checkbox" asp-for="Activity" value="true" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>

BRSK/Views/Brand/Index.cshtml
@model IEnumerable<BRSK.Models.Brand>
@{
    ViewBag.Title = "Все марки автомобилей";
}
<a asp-action="Create">Добавить бренд</a>
<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            @if (item.Activity == false)
            {
                <td style="color: lightgray">@item.BrandId</td>
            } else
            {
                <td>@item.BrandId</td>
            }
            @if (item.Activity == false)
            {
                <td style="color: lightgray">@item.Name</td>
            }
            else
            {
                <td>@item.Name</td>
            } 
            <td>|
                <a asp-action="Edit" asp-controller="Brand" asp-route-id="@item.BrandId">Изменить</a> |
                <a asp-action="Delete" asp-controller="Brand" asp-route-id="@item.BrandId">Удалить</a>
            </td>
        </tr>
    }
</table>

BRSK/Views/Home/Index.cshtml
@model IEnumerable<BRSK.Models.Model>
@{
    ViewBag.Title = "Все модели машин";
}
@*<a asp-action="Create">Добавить модель</a>*@
<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            @if (item.Brand.Activity == false)
            {
                <td style="color: lightgray">@item.Brand.Name</td>
            }
            else
            {
                <td>@item.Brand.Name</td>
            }
            @if (item.Activity == false)
            {
                <td style="color: lightgray">@item.Name</td>
            }
            else
            {
                <td>@item.Name</td>
            }
         
@*            <td>
                <a asp-action="Details" asp-controller="Home" asp-route-id="@item.ModelId">Подробнее</a> |
                <a asp-action="Delete" asp-controller="Home" asp-route-id="@item.ModelId">Удалить</a>
                <a asp-action="Edit" asp-controller="Home" asp-route-id="@item.ModelId">Изменить</a>
            </td>*@
        </tr>

    }
</table>

BRSK/Views/Model/Create.cshtml
@model BRSK.Models.PageModel
@{
    ViewBag.Title = "Добавление модели машины";
}
<form asp-action="create" asp-controller="Model">

    <select name="Brand" asp-items="Model.BrandList" class="form-control"></select>

    <div class="form-group">
        <label asp-for="ModelName" class="control-label">Название</label>
        <input type="text" asp-for="ModelName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Activity" class="control-label">Наличие</label>
        <input type="checkbox" asp-for="Activity" value="true"/>
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

BRSK/Views/Model/Delete.cshtml
@model BRSK.Models.Model
@{
    ViewBag.Title = "Удаление модели машины";
}

<div>
    <dl class="dl-horizontal">
        <dt>Наименование</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    <div>
        <form asp-controller="Model" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

BRSK/Views/Model/Edit.cshtml
@model BRSK.Models.Model
@{
    ViewBag.Title = "Редактирование модели машины";
}
<form asp-action="edit" asp-controller="Model" asp-route-id="@Model.ModelId">
    <div class="form-group">
        <input asp-for="ModelId" type="hidden" />
        <label asp-for="Name" class="control-label">Наименование</label>
        <input type="text" asp-for="Name" class="form-control" />
        <label asp-for="BrandId" class="control-label">BrendId</label>
        <input type="text" asp-for="BrandId" class="form-control" />
    </div>
  
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>

BRSK/Views/Model/Index.cshtml
@model IEnumerable<BRSK.Models.Model>
@{
    ViewBag.Title = "Все модели машин";
}
<a asp-action="Create">Добавить модель</a>
<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            @if (item.Activity == false)
            {
                <td style="color: lightgray">@item.Name</td>
            }
            else
            {
                <td>@item.Name</td>
            } 
            <td>|
                <a asp-action="Edit" asp-controller="Model" asp-route-id="@item.ModelId">Изменить</a> |
                <a asp-action="Delete" asp-controller="Model" asp-route-id="@item.ModelId">Удалить</a>
            </td>
        </tr>
    }
</table>

BRSK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BRSK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BRSK</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Model" asp-action="Index">Модели</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Index">Марки</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BRSK - <a asp-area="" asp-controller="" asp-action="">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BRSK/Views/Token/Index.cshtml
@model BRSK.AppAuthentication.AuthModels.UserModel
@{
    ViewData["Title"] = "Index";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control- label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}